### ISSUE TITLE
Hire me button on home doesn't display cursor pointer on hover

### ISSUE THREAD

**Issue by SGiumelli** [darenmalfait/daren.be#208]
**Describe the bug**

When I hover the button/link `HIRE ME Get in touch` on the home page, I expected the cursor to be a pointer to indicate interactivity but it stays at default arrow instead or text selection.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.nerdfish.be/
2. hover  `HIRE ME Get in touch`
3. See error

**Expected behaviour**
Any indication of interactivity on click

**Desktop :**
 - OS: MaxOS
 - Browser [chrome, safari]

PS: great job. It helped me so much to understand how to works with tina and next

**Comment by darenmalfait** [comment]
Thank you for reporting and I'm happy it has helped you.
